version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    target-branch: main
    commit-message:
      prefix: "deps:"
    open-pull-requests-limit: 10
    labels:
      - dependencies
    cooldown:
      default-days: 7
    groups:
      dependencies-minor-and-patch:
        dependency-type: "all"
        update-types:
          - "minor"
          - "patch"
      dependencies-major:
        dependency-type: "all"
        update-types:
          - "major"

  - package-ecosystem: pip
    directory: /.github
    schedule:
      interval: weekly
    target-branch: main
    commit-message:
      prefix: "ci:"
    open-pull-requests-limit: 5
    labels:
      - ci
      - dependencies
    cooldown:
      default-days: 7
    groups:
      ci-dependencies-minor-and-patch:
        dependency-type: "all"
        update-types:
          - "minor"
          - "patch"
      ci-dependencies-major:
        dependency-type: "all"
        update-types:
          - "major"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: main
    commit-message:
      prefix: "ci:"
    open-pull-requests-limit: 5
    labels:
      - ci
    cooldown:
      default-days: 7
    groups:
      github-actions-minor-and-patch:
        dependency-type: "all"
        update-types:
          - "minor"
          - "patch"
      github-actions-major:
        dependency-type: "all"
        update-types:
          - "major"
