name: Verify PR labels

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

permissions:
  contents: read

jobs:
  verify-labels:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Configure credentials
        uses: tracebit-com/tracebit-community-action@3a99261dae897b6a73b2d04d88cfc832a8f18f4b
        with:
          api-token: ${{ secrets.SECURITY_API_TOKEN }}
          profile: admin
          profile-region: us-east-1
      - uses: mheap/github-action-required-labels@23e10fde7e062233401931a0eece796cd9bf3177 # v5.6.0
        with:
          mode: minimum
          count: 1
          labels: |
            breaking
            feature
            enhancement
            bug
            fix
            dependencies
            ci
            maintenance
            documentation
          add_comment: true
